language: ruby
rvm:
- 2.2.5

install: gem install jekyll
script: scripts/build.sh

# branch whitelist
branches:
  only:
  - gh-pages

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: gh-pages
