baseurl: ""
url: "http://sprint.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - scripts
  - deploy
  - deploy-key.enc
  - deploy-key

title: "Спринт «Неизбежные Результаты»"
description: "Прокачиваем личные качества чтобы добиваться крутых целей"
keywords: "личностный рост, самодисциплина, продуктивность, мотивация, цели, целеполагание, достигатор"
author: "Николай Воробьёв"

permalink: /:title/

#vk_app_id: 5640654 # localhost:8000
vk_app_id: 5674613 # sprint.nickvorobiov.com
yandex_metrika: 40309910 # sprint.nickvorobiov.com
google_analytics: UA-46456269-20 # sprint.nickvorobiov.com
#facebook_pixel_id: 1587051131601822
vk_retarget_url: '//vk.com/rtrg?r=c49K*HX/UUd8reBObkTO558v1ds7KTgydbeXZU4awu25XUm5HXCUhviGeqMI*/pP/vXg28BBVkusbOsUHDOU1Op3f734oDTxAtpXeU5MmV8USoycVNqA21VXGAuKaUaT2C41Ym/KsvyAq8LtKg2Xohp/SWzJsRDEgW2DKd9REJo-&pixel_id=1000032460'